#!/bin/sh

. /home/dan/lampstack-7.1.20-0/scripts/setenv.sh

exec /home/dan/lampstack-7.1.20-0/php/sbin/.php-fpm.bin -y /home/dan/lampstack-7.1.20-0/php/etc/php-fpm.conf -p /home/dan/lampstack-7.1.20-0/php/var/ -c /home/dan/lampstack-7.1.20-0/php/etc/php.ini "$@"
