#!/bin/sh

. /home/dan/lampstack-7.1.20-0/scripts/setenv.sh
SASL_PATH="/home/dan/lampstack-7.1.20-0/common/lib/sasl2"
                export SASL_PATH
exec /home/dan/lampstack-7.1.20-0/common/sbin/.saslauthd.bin -f "/home/dan/lampstack-7.1.20-0/common/etc/sasldb2" "$@"
